apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-data-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-output-pvc
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: gp3-csi
---
# EFS StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxxx  # Replace with your EFS file system ID
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/nbedr"
---
# GP3 StorageClass for high-performance storage
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-csi
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  iops: "3000"
  throughput: "125"
  encrypted: "true"
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer