security:
  ignore-cvss-severity-below: 7.0  # Only alert on high and critical severity issues

  ignore-vulnerabilities:
    # Add specific vulnerabilities to ignore with reasons
    # Example:
    # "73169":
    #   reason: >
    #     Vulnerability in sentence-transformers is mitigated by using version >=3.1.0

  continue-on-vulnerability-error: true

  ignore-unpinned-requirements: false
