apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-data-pvc
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadOnlyMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-output-pvc
spec:
  storageClassName: azurefile-csi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: managed-csi