# GKE Service Account with Workload Identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nbedr-gke-service-account
  namespace: nbedr
  annotations:
    iam.gke.io/gcp-service-account: nbedr-gsa@your-project-id.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: service-account
---
# Google Cloud Service Account (create via gcloud or Terraform)
# gcloud iam service-accounts create nbedr-gsa \
#   --display-name="nBedR Service Account"
#
# gcloud projects add-iam-policy-binding your-project-id \
#   --member="serviceAccount:nbedr-gsa@your-project-id.iam.gserviceaccount.com" \
#   --role="roles/storage.objectAdmin"
#
# gcloud projects add-iam-policy-binding your-project-id \
#   --member="serviceAccount:nbedr-gsa@your-project-id.iam.gserviceaccount.com" \
#   --role="roles/aiplatform.user"
#
# gcloud iam service-accounts add-iam-policy-binding \
#   nbedr-gsa@your-project-id.iam.gserviceaccount.com \
#   --role roles/iam.workloadIdentityUser \
#   --member "serviceAccount:your-project-id.svc.id.goog[nbedr/nbedr-gke-service-account]"