apiVersion: v1
kind: ConfigMap
metadata:
  name: nbedr-config
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: config
data:
  # Embedding Configuration
  EMBEDDING_PROVIDER: "openai"
  EMBEDDING_MODEL: "text-embedding-3-small"
  EMBEDDING_DIMENSIONS: "1536"
  BATCH_SIZE_EMBEDDINGS: "100"
  
  # Vector Database Configuration
  VECTOR_DB_TYPE: "faiss"
  FAISS_INDEX_TYPE: "IndexFlatIP"
  
  # Processing Configuration
  CHUNK_SIZE: "512"
  CHUNKING_STRATEGY: "semantic"
  EMBEDDING_WORKERS: "2"
  EMBED_WORKERS: "2"
  
  # Rate Limiting Configuration
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_STRATEGY: "sliding_window"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "500"
  RATE_LIMIT_TOKENS_PER_MINUTE: "350000"
  RATE_LIMIT_MAX_BURST: "100"
  
  # Vector Store Rate Limiting
  VECTOR_STORE_RATE_LIMIT_ENABLED: "true"
  VECTOR_STORE_RATE_LIMIT_REQUESTS_PER_MINUTE: "300"
  VECTOR_STORE_RATE_LIMIT_MAX_BURST: "50"
  
  # Instance Coordination
  NBEDR_COORDINATION_DIR: "/tmp/nbedr_coordination"
  NBEDR_HEARTBEAT_INTERVAL: "60"
  NBEDR_DOCUMENT_COORDINATION_ENABLED: "true"
  NBEDR_DOCUMENT_LOCK_TIMEOUT_HOURS: "1"
  NBEDR_DOCUMENT_MAX_RETRIES: "3"
  
  # Prompt Template Configuration
  EMBEDDING_PROMPT_TEMPLATE: "/app/templates/embedding_prompt_template.txt"
  EMBEDDING_CUSTOM_PROMPT_VARIABLES: '{"domain": "general", "use_case": "rag_embeddings"}'
  
  # Logging
  NBEDR_LOG_LEVEL: "INFO"
  PYTHONUNBUFFERED: "1"
---
apiVersion: v1
kind: Secret
metadata:
  name: nbedr-secrets
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: secrets
type: Opaque
stringData:
  # OpenAI Configuration
  OPENAI_API_KEY: "your_openai_api_key_here"
  
  # Azure OpenAI Configuration
  AZURE_OPENAI_API_KEY: "your_azure_openai_key_here"
  AZURE_OPENAI_ENDPOINT: "https://your-resource.openai.azure.com"
  AZURE_OPENAI_DEPLOYMENT_NAME: "your-deployment-name"
  
  # Pinecone Configuration
  PINECONE_API_KEY: "your_pinecone_api_key_here"
  PINECONE_ENVIRONMENT: "your_pinecone_environment"
  
  # AWS Configuration
  AWS_ACCESS_KEY_ID: "your_aws_access_key"
  AWS_SECRET_ACCESS_KEY: "your_aws_secret_key"
  
  # Google Cloud Configuration
  GOOGLE_VERTEX_PROJECT_ID: "your-project-id"
  
  # PostgreSQL Configuration
  PGVECTOR_PASSWORD: "your_postgres_password"