apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nbedr

resources:
- namespace.yaml
- configmap.yaml
- templates-configmap.yaml
- deployment.yaml
- service.yaml
- pvc.yaml

images:
- name: nbedr
  newName: nbedr
  newTag: latest

commonLabels:
  app.kubernetes.io/name: nbedr
  app.kubernetes.io/part-of: nbedr-system