apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-data-pvc
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-output-pvc
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nbedr-coordination-pvc
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: coordination
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
# Optional: PostgreSQL PVC if using PGVector
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nbedr
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard