apiVersion: v1
kind: Service
metadata:
  name: nbedr-service
  namespace: nbedr
  labels:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: nbedr
    app.kubernetes.io/component: worker
---
# Optional: PostgreSQL Service if using PGVector
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nbedr
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
---
# PostgreSQL Deployment (optional)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: nbedr
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/component: database
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10002
        runAsGroup: 10002
        fsGroup: 10002
      containers:
      - name: postgres
        image: docker.io/pgvector/pgvector:0.8.0-pg16
        securityContext:
          runAsNonRoot: true
          runAsUser: 10002
          runAsGroup: 10002
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: POSTGRES_DB
          value: vectordb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nbedr-secrets
              key: PGVECTOR_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: postgres-tmp
          mountPath: /tmp
        - name: postgres-run
          mountPath: /var/run/postgresql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: postgres-tmp
        emptyDir: {}
      - name: postgres-run
        emptyDir: {}